#!/usr/bin/env node
// skunks/oneshot/scripts/build.mjs: builds the page into docs/oneshot/ (GitHub Pages, branch main, folder /docs).
//   web/main.ts (+ src/spend.ts, src/wots.ts, src/outputs.ts, src/templates.ts, Fleet, @noble/hashes)
//     -> docs/oneshot/oneshot.js   one classic script (IIFE, not a module, so the page also works from file://)
//   web/sigma.ts (sigmastate-js 0.6.3 only) -> docs/oneshot/oneshot-sigma.js, loaded by the page only for a P2SH
//     spend; minified (the published sigmastate-js is a 13 MB Scala.js fastopt build: nothing to read in it), with
//     one shim: an empty module for Node's `crypto`, which sigmajs-crypto-facade requires and does not use in a
//     browser (it prefers self.crypto); without it esbuild stops with: Could not resolve "crypto"
//   web/index.html -> docs/oneshot/index.html, web/style.css -> docs/oneshot/oneshot.css (copied unchanged)
// oneshot.js is not minified, so it can be read and diffed against the source; paths in it are relative to
// skunks/oneshot.
//   node scripts/build.mjs           build into docs/oneshot/
//   node scripts/build.mjs --check   build twice into temporary directories and compare the two builds with each
//                                    other and with docs/oneshot/ (exit 1 on any difference): reproducible, and the
//                                    committed page is the build of the committed source
import { build, version } from 'esbuild';
import { copyFileSync, mkdirSync, mkdtempSync, readFileSync, rmSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { gzipSync } from 'node:zlib';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const pkg = join(dirname(fileURLToPath(import.meta.url)), '..');
const docs = join(pkg, '..', '..', 'docs', 'oneshot');
const FILES = ['index.html', 'oneshot.js', 'oneshot-sigma.js', 'oneshot.css'];
const sha = (f) => createHash('sha256').update(readFileSync(f)).digest('hex');

// sigmajs-crypto-facade (a sigmastate-js dependency) vendors noble-secp256k1 v1, which does require("crypto") at load
// and then prefers self.crypto (Web Crypto) when `self` exists; an empty module is enough (recon/bundle.mjs).
const emptyCrypto = { name: 'empty-node-crypto', setup(b) {
  b.onResolve({ filter: /^crypto$/ }, () => ({ path: 'crypto', namespace: 'empty' }));
  b.onLoad({ filter: /.*/, namespace: 'empty' }, () => ({ contents: 'module.exports = {};', loader: 'js' }));
} };

async function buildInto(out) {
mkdirSync(out, { recursive: true });
await build({
  absWorkingDir: pkg,
  entryPoints: ['web/main.ts'],
  outfile: join(out, 'oneshot.js'),
  bundle: true,
  format: 'iife',
  platform: 'browser',
  target: 'es2020',
  minify: false,
  sourcemap: false,
  charset: 'utf8',
  legalComments: 'inline',
  banner: { js: `// oneshot.js: GENERATED by skunks/oneshot/scripts/build.mjs (esbuild ${version}) from skunks/oneshot/web/main.ts;\n// do not edit. Source and tests: skunks/oneshot/ in the skunkyard repository.` },
  logLevel: 'warning',
});
await build({
  absWorkingDir: pkg,
  entryPoints: ['web/sigma.ts'],
  outfile: join(out, 'oneshot-sigma.js'),
  bundle: true,
  format: 'iife',
  platform: 'browser',
  target: 'es2020',
  minify: true,
  sourcemap: false,
  charset: 'utf8',
  legalComments: 'inline',
  banner: { js: `// oneshot-sigma.js: GENERATED by skunks/oneshot/scripts/build.mjs (esbuild ${version}) from skunks/oneshot/web/sigma.ts:\n// sigmastate-js 0.6.3 (npm), minified, Node's crypto replaced by an empty module. Loaded only for a P2SH spend.` },
  plugins: [emptyCrypto],
  logLevel: 'warning',
});
copyFileSync(join(pkg, 'web', 'index.html'), join(out, 'index.html'));
copyFileSync(join(pkg, 'web', 'style.css'), join(out, 'oneshot.css'));
}

if (process.argv[2] === '--check') {
  const dirs = [mkdtempSync(join(tmpdir(), 'oneshot-build-a-')), mkdtempSync(join(tmpdir(), 'oneshot-build-b-'))];
  let bad = 0;
  try {
    for (const d of dirs) await buildInto(d);
    for (const f of FILES) {
      const [a, b] = dirs.map((d) => sha(join(d, f)));
      let c = 'missing';
      try { c = sha(join(docs, f)); } catch { /* not built yet */ }
      const ok = a === b && b === c;
      if (!ok) bad++;
      console.log(`${ok ? 'SAME' : 'DIFF'} ${f} build1 ${a.slice(0, 16)} build2 ${b.slice(0, 16)} docs/oneshot ${c.slice(0, 16)}`);
    }
  } finally {
    for (const d of dirs) rmSync(d, { recursive: true, force: true });
  }
  console.log(bad === 0 ? 'BUILD-CHECK: PASS (two builds identical, equal to docs/oneshot/)' : `BUILD-CHECK: FAIL (${bad} files differ)`);
  process.exit(bad === 0 ? 0 : 1);
}

await buildInto(docs);
for (const f of FILES) {
  const b = readFileSync(join(docs, f));
  console.log(`docs/oneshot/${f} ${b.length} bytes (gzip -9 ${gzipSync(b, { level: 9 }).length}) sha256 ${sha(join(docs, f))}`);
}
