// scripts/templates.mjs: write src/templates.ts from vectors/wots-n*-w*.json (the compiled q2/wots-constant.es tree
// per (n, w) with the 32 commitment bytes zeroed, and their byte offset). Run after vectors/gen.sh:
//   node scripts/templates.mjs
// The test checks that src/templates.ts agrees with the vectors, so a stale file fails `npm test`.
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const files = readdirSync(join(root, 'vectors')).filter((f) => /^wots-n\d+-w\d+\.json$/.test(f)).sort();
const lines = [
  '// GENERATED by scripts/templates.mjs from vectors/*.json; do not edit. q2/wots-constant.es compiled with',
  '// sigma-state 6.0.7 for each (n, w), the 32-byte commitment constant zeroed at `offset`.',
  'export const TREE_TEMPLATES: Record<string, { offset: number; hex: string; templateHash: string }> = {',
];
for (const f of files) {
  const v = JSON.parse(readFileSync(join(root, 'vectors', f), 'utf8'));
  lines.push(`  'n${v.n}-w${v.w}': { offset: ${v.tree.commitmentOffset}, templateHash: '${v.tree.templateHash}',`);
  lines.push(`    hex: '${v.tree.templateHex}' },`);
}
lines.push('};', '');
writeFileSync(join(root, 'src', 'templates.ts'), lines.join('\n'));
console.log(`wrote src/templates.ts (${files.length} templates)`);
